name: Generate Podcast Feeds
on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # 1. Checkout code with full history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Show workspace structure and files
      - name: Show workspace structure
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Looking for feed.py and YAML files..."
          find . -name "feed.py" -o -name "*.yaml" -o -name "*.yml"

      # 3. Show YAML file content (update filename if needed)
      - name: Show YAML file content
        run: cat feed.yaml
        # Replace 'your_yaml_file.yaml' with the actual YAML filename

      # 4. Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 5. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install pyyaml; fi

      # 6. Run the feed generator
      - name: Generate feed
        run: |
          echo "Running from: $(pwd)"
          python feed.py

      # 7. Commit and push changes if any
      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-generated feed update"
          git push
