name: Generate Podcast Feeds
on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      # 1. Checkout with full history
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Get all history and tags
          
      # 2. Debug: Show exact file structure
      - name: Verify files exist
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          echo "Checking for feed.py..."
          find . -name feed.py -type f
          echo "Python files in repo:"
          find . -name "*.py" -type f
          
      # 3. Setup Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          
      # 5. Run the feed generator
      - name: Generate feed
        run: |
          echo "Running from: $(pwd)"
          python feed.py
          
      # 6. Push changes if any
      - name: Commit and push changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-generated feed update"
          git push
