name: Generate Podcast Feeds
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # Required to push changes
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Gets full repository history
          
      - name: Verify Files
        run: |
          ls -la
          pwd
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: Debug Path
        run: find $GITHUB_WORKSPACE -name "feed.py"
          
      - name: Generate Feed
        run: python feed.py  # Runs from repository root
          
      - name: Commit and Push Changes
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Auto-generated feed update"
          git push
